# Server configuration
server:
  port: "8080"

# Database connection settings
database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "localportfoliomanager"
  sslmode: "disable"

# Web scraper settings
scraper:
  max_pages: 10
  timeout: 30
  delay: 2